AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  candidate_invite

  Sample SAM Template for candidate_invite

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Parameters:
  SupabaseUrl:
    Description: "Supabase url for client connection"
    Type: String
  SupabaseKey:
    Description: "Supabase key for client connection"
    Type: String
  EnvName:
    Description: "The environment name for the stack"
    Type: String
    Default: dev
Resources:
  # Lambda Layer
  utilsLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - nodejs22.x
      ContentUri: functions/utils/nodejs/
      Description: Lambda layer for ats utils
      LayerName: !Sub "Antstack-ATS-utilsLambdaLayer-${EnvName}"
    Metadata:
      BuildMethod: nodejs22.x
  SendInvite:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: functions/app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Layers:
        - !Ref utilsLambdaLayer
      Events:
        SendEmail:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /invite
            Method: post            
      Policies:
        - AmazonSESFullAccess
      Environment:
        Variables:
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_KEY: !Ref SupabaseKey
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - functions/app.ts
        External:
          - '@aws-sdk/client-ses'
          - "@supabase/supabase-js"
  
Outputs:
  InviteApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/invite"
